version: '3.1'
volumes:
  pgdata:
services:
  postgres:
    image: postgres:1t

    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=will_crusaders
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/dumps:/docker-entrypoint-initdb.d